[programs.devnet]
solana_twitter = "F4MpghVxRA1hu6aot5NAwdmLFK2zQnArNwPYnuKMStep"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/camachocris/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"